# Required
version: 2

# Image to use
build:
  image: testing

# Configuration
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  
python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
